import type { Employee, TransferRecord, PLIRecord, VacancyRecord, AIInsight } from '../types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    employeeCode: 'EMP001',
    name: 'Rajesh Kumar',
    fatherName: 'Suresh Kumar',
    gender: 'Male',
    dob: '1985-05-15',
    doj: '2010-03-01',
    dor: '2045-05-15',
    status: 'Active',
    state: 'Rajasthan',
    branch: 'Jaipur',
    edition: 'Jaipur Edition',
    location: 'Main Bureau',
    department: 'Editorial',
    profile: 'Senior Reporter',
    subProfile: 'Political',
    employeeType: 'Fixed',
    education: 'MA Journalism',
    email: 'rajesh.kumar@media.com',
    mobile: '9876543210',
    pan: 'ABCDE1234F',
    zimbeaId: 'ZIM001',
    grossSalary: 65000,
    voucher: 5000,
    pli: 12000,
    partB: 3000,
    totalCTC: 85000,
  },
  {
    id: '2',
    employeeCode: 'EMP002',
    name: 'Priya Sharma',
    fatherName: 'Vijay Sharma',
    gender: 'Female',
    dob: '1990-08-22',
    doj: '2015-07-10',
    dor: '2050-08-22',
    status: 'Active',
    state: 'Rajasthan',
    branch: 'Udaipur',
    edition: 'Udaipur Edition',
    location: 'City Bureau',
    department: 'Editorial',
    profile: 'Reporter',
    employeeType: 'Fixed',
    education: 'BA Mass Comm',
    email: 'priya.sharma@media.com',
    mobile: '9876543211',
    pan: 'XYZAB5678C',
    zimbeaId: 'ZIM002',
    grossSalary: 45000,
    voucher: 3000,
    pli: 8000,
    partB: 2000,
    totalCTC: 58000,
  },
  {
    id: '3',
    employeeCode: 'EMP003',
    name: 'Amit Singh',
    fatherName: 'Ramesh Singh',
    gender: 'Male',
    dob: '1970-11-05',
    doj: '1995-01-15',
    dor: '2030-11-05',
    status: 'Active',
    state: 'Rajasthan',
    branch: 'Jodhpur',
    edition: 'Jodhpur Edition',
    location: 'Main Bureau',
    department: 'Editorial',
    profile: 'Bureau Chief',
    employeeType: 'Fixed',
    education: 'MA Political Science',
    email: 'amit.singh@media.com',
    mobile: '9876543212',
    pan: 'PQRST9012D',
    zimbeaId: 'ZIM003',
    grossSalary: 85000,
    voucher: 8000,
    pli: 25000,
    partB: 5000,
    totalCTC: 123000,
  },
  {
    id: '4',
    employeeCode: 'EMP004',
    name: 'Sneha Gupta',
    gender: 'Female',
    dob: '1995-02-14',
    doj: '2023-09-01',
    status: 'Probation',
    state: 'Rajasthan',
    branch: 'Jaipur',
    edition: 'Jaipur Edition',
    location: 'Digital Desk',
    department: 'Digital',
    profile: 'Video Journalist',
    employeeType: 'Fixed',
    education: 'Diploma in Film Making',
    email: 'sneha.gupta@media.com',
    mobile: '9876543213',
    pan: 'LMNOP3456E',
    grossSalary: 35000,
    voucher: 2000,
    pli: 5000,
    partB: 1000,
    totalCTC: 43000,
  },
  {
    id: '5',
    employeeCode: 'EMP005',
    name: 'Vikram Rathore',
    gender: 'Male',
    dob: '1988-07-30',
    doj: '2018-04-12',
    dor: '2048-07-30',
    lwd: '2024-01-15',
    status: 'Left',
    state: 'Rajasthan',
    branch: 'Jaipur',
    edition: 'Jaipur Edition',
    location: 'Main Bureau',
    department: 'Editorial',
    profile: 'Photographer',
    employeeType: 'Fixed',
    education: 'BSc Photography',
    email: 'vikram.rathore@media.com',
    mobile: '9876543214',
    pan: 'FGHIJ7890G',
    grossSalary: 40000,
    voucher: 2500,
    pli: 6000,
    partB: 1500,
    totalCTC: 50000,
  },
];

export const mockVacancies: VacancyRecord[] = [
  { id: 'v1', state: 'Rajasthan', branch: 'Jaipur', department: 'Editorial', profile: 'Reporter', sanctionedStrength: 12, availableStrength: 8, vacancy: 4, vacancyPercentage: 33.33 },
  { id: 'v2', state: 'Rajasthan', branch: 'Udaipur', department: 'Editorial', profile: 'Photographer', sanctionedStrength: 4, availableStrength: 2, vacancy: 2, vacancyPercentage: 50.0 },
  { id: 'v3', state: 'Rajasthan', branch: 'Jodhpur', department: 'Digital', profile: 'Video Journalist', sanctionedStrength: 3, availableStrength: 3, vacancy: 0, vacancyPercentage: 0 },
  { id: 'v4', state: 'Rajasthan', branch: 'Jaipur', department: 'Editorial', profile: 'Sub Editor', sanctionedStrength: 6, availableStrength: 5, vacancy: 1, vacancyPercentage: 16.67 },
];

export const mockAIInsights: AIInsight[] = [
  { id: 'i1', category: 'vacancy', insight: 'Jaipur Branch has 4 Reporter vacancies (33% gap). Immediate hiring recommended.', severity: 'high' },
  { id: 'i2', category: 'attrition', insight: 'Udaipur Branch attrition rate is 18% in the last 6 months, above the 12% industry average.', severity: 'medium' },
  { id: 'i3', category: 'retirement', insight: '27 employees across all branches will retire in the next 3 years. Succession planning needed for 5 Bureau Chiefs.', severity: 'high' },
  { id: 'i4', category: 'cost', insight: 'Digital Division salary cost has increased by 15% YoY, now representing 31% of total payroll.', severity: 'low' },
  { id: 'i5', category: 'general', insight: 'Data completeness score is at 92%. 74 employees are missing PAN or Mobile details.', severity: 'medium' },
];

export const mockTransfers: TransferRecord[] = [
  {
    id: 't1',
    employeeId: '1',
    employeeCode: 'EMP001',
    employeeName: 'Rajesh Kumar',
    transferDate: '2023-04-01',
    oldState: 'Rajasthan',
    oldBranch: 'Udaipur',
    oldLocation: 'City Bureau',
    oldProfile: 'Reporter',
    newState: 'Rajasthan',
    newBranch: 'Jaipur',
    newLocation: 'Main Bureau',
    newProfile: 'Senior Reporter',
    reason: 'Promotion and Bureau Upgrade',
  },
  {
    id: 't2',
    employeeId: '3',
    employeeCode: 'EMP003',
    employeeName: 'Amit Singh',
    transferDate: '2020-01-15',
    oldState: 'Rajasthan',
    oldBranch: 'Jaipur',
    oldLocation: 'Main Bureau',
    oldProfile: 'Senior Reporter',
    newState: 'Rajasthan',
    newBranch: 'Jodhpur',
    newLocation: 'Main Bureau',
    newProfile: 'Bureau Chief',
    reason: 'Administrative Promotion',
  },
];

export const mockPLIRecords: PLIRecord[] = [
  { id: 'p1', employeeId: '1', employeeCode: 'EMP001', employeeName: 'Rajesh Kumar', month: 'March', year: 2024, target: 100, achievement: 120, pliPercentage: 15, pliAmount: 12000 },
  { id: 'p2', employeeId: '2', employeeCode: 'EMP002', employeeName: 'Priya Sharma', month: 'March', year: 2024, target: 100, achievement: 95, pliPercentage: 10, pliAmount: 8000 },
  { id: 'p3', employeeId: '3', employeeCode: 'EMP003', employeeName: 'Amit Singh', month: 'March', year: 2024, target: 100, achievement: 135, pliPercentage: 20, pliAmount: 25000 },
  { id: 'p4', employeeId: '4', employeeCode: 'EMP004', employeeName: 'Sneha Gupta', month: 'March', year: 2024, target: 100, achievement: 80, pliPercentage: 5, pliAmount: 5000 },
];

export const generateMockEmployees = (count: number): Employee[] => {
  const employees: Employee[] = [];
  const states = ['Rajasthan', 'Madhya Pradesh', 'Gujarat', 'Delhi'];
  const branches = ['Jaipur', 'Udaipur', 'Jodhpur', 'Bhopal', 'Indore', 'Ahmedabad', 'Surat', 'New Delhi'];
  const profiles = ['Reporter', 'Senior Reporter', 'Bureau Chief', 'Photographer', 'Video Journalist', 'Sub Editor', 'Stringer'];
  const statuses: Employee['status'][] = ['Active', 'Active', 'Active', 'Probation', 'Contract', 'Stringer', 'Left'];

  for (let i = 6; i <= count; i++) {
    const state = states[Math.floor(Math.random() * states.length)];
    const branch = branches[Math.floor(Math.random() * branches.length)];
    const profile = profiles[Math.floor(Math.random() * profiles.length)];
    const status = statuses[Math.floor(Math.random() * statuses.length)];
    const gross = Math.floor(Math.random() * 50000) + 30000;

    employees.push({
      id: `${i}`,
      employeeCode: `EMP${String(i).padStart(3, '0')}`,
      name: `Employee ${i}`,
      gender: Math.random() > 0.5 ? 'Male' : 'Female',
      dob: `19${Math.floor(Math.random() * 40) + 60}-${String(Math.floor(Math.random() * 12) + 1).padStart(2, '0')}-${String(Math.floor(Math.random() * 28) + 1).padStart(2, '0')}`,
      doj: `20${Math.floor(Math.random() * 24)}-${String(Math.floor(Math.random() * 12) + 1).padStart(2, '0')}-${String(Math.floor(Math.random() * 28) + 1).padStart(2, '0')}`,
      status,
      state,
      branch,
      edition: `${branch} Edition`,
      location: 'Main Bureau',
      department: 'Editorial',
      profile,
      employeeType: status === 'Stringer' ? 'Stringer' : 'Fixed',
      email: `emp${i}@media.com`,
      mobile: `98765${String(Math.floor(Math.random() * 10000)).padStart(4, '0')}`,
      grossSalary: gross,
      totalCTC: Math.floor(gross * 1.3),
    });
  }
  return employees;
};